[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build.environment]
  RESEND_API_KEY = "re_dCC8Rj7A_PEyBm9yVSd2DbHKXhS5zzgue"

[build]
  command = "npm run build && npm run export"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

